
services:
  deepseek-free-api:
    container_name: deepseek-free-api
    image: vinlic/deepseek-free-api:latest
    restart: always
    ports:
      - "8082:8000"
    environment:
      - TZ=Asia/S
      - hanghai



# source：https://github.com/LLM-Red-Team/deepseek-free-api?tab=readme-ov-file
# docker compose up -d
# docker compose down


