


services:
  joern:
    image: ghcr.io/joernio/joern:nightly
    container_name: joern-server
    ports:
      - "18082:18082"
    volumes:
      - ./:/app:rw
      - /tmp:/tmp
    working_dir: /app
    command: joern --server --server-port 18082 --server-auth-username admin --server-auth-password admin
    restart: unless-stopped


# docker compose up -d

